# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Describe < Formula
  desc "Command-line tool that generates Markdown documentation from a directory"
  homepage "https://github.com/rodlaf/describe"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rodlaf/describe/releases/download/v1.0.4/describe_darwin_amd64.tar.gz"
      sha256 "e94dbe5236bf40101bd9176bccc5c3d9197865edfc4380ceef5c6850a9341182"

      def install
        bin.install 'describe'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rodlaf/describe/releases/download/v1.0.4/describe_darwin_arm64.tar.gz"
      sha256 "502c5c511f5d1f59c6be88ec4fd226e6ab899cd4b33347df1ce2ca3271f57681"

      def install
        bin.install 'describe'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rodlaf/describe/releases/download/v1.0.4/describe_linux_amd64.tar.gz"
        sha256 "b626f7c6c4bc95380110bad777d0f593e2a6be6a55fbbe4cca6012c307292a76"

        def install
          bin.install 'describe'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rodlaf/describe/releases/download/v1.0.4/describe_linux_arm64.tar.gz"
        sha256 "c8af19e54da807388dd5105f548f0d52c39c515bd29ed58eec52d46b5d4be5dc"

        def install
          bin.install 'describe'
        end
      end
    end
  end

  test do
    system '#{bin}/describe', '--help'
  end
end
