# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Describe < Formula
  desc "Command-line tool that generates Markdown documentation from a directory"
  homepage "https://github.com/rodlaf/describe"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rodlaf/describe/releases/download/v1.0.3/describe_darwin_amd64.tar.gz"
      sha256 "9ef6c584a753e50535e2677c899db239559beb52bf21f2a4f17c8985237c925c"

      def install
        bin.install 'describe'
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rodlaf/describe/releases/download/v1.0.3/describe_darwin_arm64.tar.gz"
      sha256 "13480a38f882435fa6f8eacccafe30c305ab5927f63ebdbfb49abdc38f1a9749"

      def install
        bin.install 'describe'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rodlaf/describe/releases/download/v1.0.3/describe_linux_amd64.tar.gz"
        sha256 "7c915911d42be66160d97a4865bd3222fb0f8fe107eb3127336e6b61eaa08809"

        def install
          bin.install 'describe'
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rodlaf/describe/releases/download/v1.0.3/describe_linux_arm64.tar.gz"
        sha256 "6b893a1f591a805fcc6968b99b496c34ac1121447015b84a400895e3f06cb2be"

        def install
          bin.install 'describe'
        end
      end
    end
  end

  test do
    system '#{bin}/describe', '--help'
  end
end
